language: cpp
compiler:
  - gcc
#  - clang
env:
    # These are used by .travis-cmake.sh to set a configuration
    - STP_CONFIG=STATIC_LIB
    - STP_CONFIG=DYNAMIC_LIB
    - STP_CONFIG=DYNAMIC_AND_STATIC_LIB
    - STP_CONFIG=STATIC_BINARY
    - STP_CONFIG=RELEASE
    - STP_CONFIG=NO_BOOST
    - STP_CONFIG=CPP11
before_install:
#get neccessary libraries and headers
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install
  - sudo apt-get install -y cmake git zlib1g-dev
# get and install minisat
  - mkdir minisat_git && cd minisat_git
  - git clone https://github.com/stp/minisat
  - cd minisat
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../..
# get LIT from pip
  - sudo pip install lit
# Initialise our submodules
  - git submodule init
  - git submodule update
#set up build environment
  - mkdir build && cd build
  - mkdir simple_example
  - mkdir stp && cd stp
script:
# Build STP
  - ../../scripts/travis-cmake.sh ../../
  - make VERBOSE=1
  - make check
# Build example project. We assume that the build installed itself to the CMake
# user package registry (~/.cmake/packages/)
  - cd ../simple_example
  - cmake -G "Unix Makefiles" -DUSE_STP_SHARED_LIBRARY=$( test -f ../stp/lib/libstp.so && echo ON || echo OFF) ../../examples/simple
  - make VERBOSE=1
  - ./stp-example
